# Generated by Django 4.0.3 on 2022-04-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('HS', 'Highest'), ('HG', 'High'), ('MI', 'Medium'), ('LW', 'Low'), ('LS', 'Lowest')], max_length=100, verbose_name='priorities of Card')),
                ('status', models.CharField(choices=[('TD', 'To Do'), ('IP', 'In progress'), ('DN', 'Done'), ('IR', 'In review'), ('AR', 'Approved'), ('NS', 'Not sure')], max_length=100, verbose_name='status of card')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ('title',),
            },
        ),
    ]
