# Generated by Django 4.0.3 on 2022-04-12 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart_items', '0001_initial'),
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Cart_items.list', verbose_name='cards of a list'),
        ),
        migrations.AddField(
            model_name='card',
            name='member',
            field=models.ManyToManyField(related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
