# Generated by Django 4.0.3 on 2022-04-11 19:40

import Workspace.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('upload_to', models.ImageField(upload_to='', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('category_type', models.CharField(choices=[('PL', 'POPULAR'), ('SM', 'SMALL BUSINESS'), ('DS', 'DESIGN'), ('ED', 'EDUCATION'), ('EI', 'ENGINEERING IT'), ('MK', 'MARKETING'), ('HR', 'HUMAN RESOURCES'), ('OP', 'OPERATIONS'), ('SC', 'SALES CRM')], default=Workspace.models.default_category, max_length=100, verbose_name='Category Types')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to=settings.AUTH_USER_MODEL, verbose_name='members of workspace')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
            },
        ),
    ]
