# Generated by Django 4.0.3 on 2022-04-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
